# https://github.com/elastic/elasticsearch-docker
# from daocloud.io/library/
FROM daocloud.io/library/elasticsearch:5.3.0

# Add your elasticsearch plugins setup here
# Example: RUN elasticsearch-plugin install analysis-icu
